LOSS_TYPE: "Contrastive"     # Options: "Circle", "MultiSimilarity", "Contrastive"
EARLY_STOP: false                # Enable or disable early stopping
PATIENCE: 5                      # Epochs to wait for improvement before stopping
NUM_EPOCHS: 60                   # Total training epochs
BATCHSIZE: 32                    # Training batch size
LR: 0.0001                       # Learning rate
WEIGHT_DECAY: 0.0001             # Optimizer weight decay
PRETRAINED: false              # Use pretrained model weights
