PREPROCESSING:
  batch_size: 64
  image_dir: data/celeba/img_align_celeba
  image_size: 100
  label_file: data/celeba/identity_CelebA.txt
  m_per_sample: 2
  partition_file: data/celeba/list_eval_partition.csv
TRAINING_ARCFACE:
  embedding_size: 256
  lr: 1.5637654727242717e-05
  margin: 0.28354689792532023
  num_epochs: 100
  patience: 20
  scale: 39.4070176326951
  scheduling: false
  weight_decay: 0.00021016419155668912
