PREPROCESSING:
  # Input file
  image_dir: data/celeba/img_align_celeba
  label_file: data/celeba/identity_CelebA.txt
  partition_file: data/celeba/list_eval_partition.csv
  # Data Loader settings
  batch_size: 32
  m_per_sample: 2

TRAINING:
  # Optimizer
  lr: 0.1
  weight_decay: 0.1
  scheduling: cosine  # Options: onecycle - reduce_on_plateau - cosine
  # Training
  num_epochs: 20
  patience: 5
  # Loss
  loss_type: contrastive  # Options: contrastive - multisimilarity - arcface - margin
  # Network
  hidden_dimension: [512,256]
  embedding_dimension: 128