PREPROCESSING:
  image_dir: data/celeba/img_align_celeba
  label_file: data/celeba/identity_CelebA.txt
  partition_file: data/celeba/list_eval_partition.csv
  batch_size: 16
  m_per_sample: 16

TRAINING:
  # Optimizer
  lr: 0.001
  weight_decay: 0.01
  # Training
  num_epochs: 10
  patience: 5
  # Loss
  loss_type: contrastive
  # Network
  hidden_dimension: [1024,512]
  embedding_dimension: 256
